// ---------------------------------------------------------------- //
// This file is autogenerated by pioasm version 2.2.0; do not edit! //
// ---------------------------------------------------------------- //

#pragma once

#if !PICO_NO_HARDWARE
#include "hardware/pio.h"
#endif

// ------------ //
// tc_audio_i2s //
// ------------ //

#define tc_audio_i2s_wrap_target 0
#define tc_audio_i2s_wrap 1
#define tc_audio_i2s_pio_version 1

#define tc_audio_i2s_offset_entry_point 0u

static const uint16_t tc_audio_i2s_program_instructions[] = {
            //     .wrap_target
    0x6002, //  0: out    pins, 2         side 0
    0x1000, //  1: jmp    0               side 1
            //     .wrap
};

#if !PICO_NO_HARDWARE
static const struct pio_program tc_audio_i2s_program = {
    .instructions = tc_audio_i2s_program_instructions,
    .length = 2,
    .origin = -1,
    .pio_version = tc_audio_i2s_pio_version,
#if PICO_PIO_VERSION > 0
    .used_gpio_ranges = 0x0
#endif
};

static inline pio_sm_config tc_audio_i2s_program_get_default_config(uint offset) {
    pio_sm_config c = pio_get_default_sm_config();
    sm_config_set_wrap(&c, offset + tc_audio_i2s_wrap_target, offset + tc_audio_i2s_wrap);
    sm_config_set_sideset(&c, 1, false, false);
    return c;
}

static inline void tc_audio_i2s_program_init(PIO pio, uint sm, uint offset, uint data_lrclk_pin_base, uint bclk_pin) {
    pio_sm_config c = tc_audio_i2s_program_get_default_config(offset);
    sm_config_set_out_pins(&c, data_lrclk_pin_base, 2);
    sm_config_set_sideset_pins(&c, bclk_pin);
    sm_config_set_out_shift(&c, false, true, 32);
    sm_config_set_fifo_join(&c, PIO_FIFO_JOIN_TX);
    pio_sm_init(pio, sm, offset, &c);
    pio_sm_set_consecutive_pindirs(pio, sm, data_lrclk_pin_base, 2, true);
    pio_sm_set_consecutive_pindirs(pio, sm, bclk_pin, 1, true);
    pio_sm_set_pins(pio, sm, 0);
    pio_sm_exec(pio, sm, pio_encode_jmp(offset + tc_audio_i2s_offset_entry_point));
}

#endif

